-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('MESSAGE', 'APPLICATION_APPROVED', 'APPLICATION_REJECTED', 'APPLICATION_UPDATE', 'APPLICATION_RESPONSE', 'APPLICATION_NEW', 'NEW_TICKET', 'TICKET_UPDATE', 'TASK_ASSIGNED', 'TASK_COMPLETED', 'PAYMENT_DUE', 'PAYMENT_COMPLETED') NOT NULL;
